version: '3'
services:
    redis:
        image: redis:3.0.7
        restart: always
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/var/lib/redis
    rabbitmq:
        build: rabbitmq/
        restart: always
        hostname: rabbitmq
        ports:
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
            - ./rabbitmq/setup/:/setup
        tty: true
        environment:
            - RABBIT_HOST=${RABBIT_HOST}
            - RABBIT_PORT=${RABBIT_PORT}
            - RABBITMQ_DEFAULT_USER=${RABBIT_SUPER_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBIT_SUPER_PASSWORD}
            - RABBITMQ_DEFAULT_VHOST=${RABBIT_VHOST}
            - RABBITMQ_SUB_USER=${RABBIT_SUP_USER}
            - RABBITMQ_SUB_PASS=${RABBIT_SUP_PASSWORD}
            - RABBITMQ_TAG=${RABBITMQ_TAG}
    postgres:
        image: postgres:9.5.2
        restart: always
        hostname: postgres
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - postgres-data:/var/lib/posgresql
volumes:
    rabbitmq-data:
        driver: local
    redis-data:
        driver: local
    postgres-data:
        driver: local
