version: '2'
services:
    redis:
        image: redis:3.0.7
        restart: always
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/var/lib/redis

    rabbitmq:
        build: rabbitmq/
        restart: always
        hostname: rabbitmq
        ports:
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        tty: true
    postgres:
        image: postgres:9.5.2
        restart: always
        hostname: postgres
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - postgres-data:/var/lib/posgresql
volumes:
    rabbitmq-data:
        driver: local
    redis-data:
        driver: local
    postgres-data:
        driver: local
